name: scraper-gm-indices-yahoo-finance

on:
  workflow_dispatch:
  schedule:
    - cron: '9 21 * * 1-5' # runs once at 20:09 UTC

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          
      - name: execute py script 
        run: pipenv run python general_market_indices_update.py
        env: 
          DW_API_KEY: ${{ secrets.DW_API_KEY }}
        
          
      # push to git repo
      - name: Add and commit
        id: add_commit
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: Automated
          committer_email: actions@users.noreply.github.com
          message: "Latest data"
